#The log statements minimum level that will be printed in the console.
#Spigot does not allow printing logs under the 'INFO' level, then all below levels will be printed in the 'INFO' level at runtime.
#Values: OFF, SEVERE, WARNING, INFO, CONFIG, FINE, FINER, FINEST, ALL
logging_level: INFO

#If the player's client is set to a language which isn't either built into this plugin or manually implemented,
#this is the one it'll default.
default_language: "en"

#The path where the plugin's data and files are stored (Does not include this file)
config_folder: "plugins/Landlords"

#The maximum group level a player mush be a member of to receive a message.
# Special arguments: noOne = no message sent.
#                    all = all players in the server.
#                    responsible = only the player who resized the region.
#                    members = all member of the region regardless their permission level.
#                    Any integer will just define a maximum level reach.
messages_reach:
  region_resize: 1
  region_updatePermisions: 1

totems:
  #Defines the groups level a player is assigned to when they place a totem.
  default_group_level: 1

  #The item to use to feed a totem.
  upgrade_item:
    item: DIAMOND     #Must be defined as a Spigot's Material enum value. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
    consume: true     #weather or not the item gets consumed when used.
    count: 1          #how many items to consume if the above is true.

  #The item to hit a totem with in order to force expansion to one direction.
  directional_item: BLAZE_ROD

  #How long it takes to be able to interact with a totem once you've already updated it or downgraded it.
  #Defined in ticks.
  interact_cooldown: 400

  #Value between 0 and 1 that corresponds to the percentage of upgrade_item to drop when destroying a totem or downgrading it.
  drop_back_rate: 0.5

  particles:
    #Merely visual settings. Set the particle effect to display when a totem is placed.
    enable:
      type: REVERSE_PORTAL    #Must be defined as a Spigot's Particle enum value. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
      count: 400
      delta: [0.0, 0.0, 0.0]

    hurt:
      type: DRAGON_BREATH     #Must be defined as a Spigot's Particle enum value. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
      count: 120
      delta: [.3, .3, .3]

    feed:
      type: PORTAL            #Must be defined as a Spigot's Particle enum value. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
      count: 250
      delta: [.3, .3, .3]

    disable:
      type: CRIT              #Must be defined as a Spigot's Particle enum value. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
      count: 300
      delta: [.6, .6, .6]

  #List of the effects an arrow mist have to destroy a totem EndCrystal. Must be defined as the name of the fields of
  #the Spigot's PotionEffectType class https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html or a custom registered effect.
  #An empty array means a normal arrow is enough to destroy an EndCrystal.
  destroy_arrow_effects: ["POISON"]


deeds:
  #Determines which item you must right-click a totem End Crystal with in order to obtain its deeds.
  #(Deeds will always be a book and quill, so leaving it as "WRITABLE_BOOK" is recommended)
  #Must be defined as a Spigot's Material enum value. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  exchange_item: WRITABLE_BOOK

  #How many players fit in a single page of a book and quill when modifying a region's permissions through deeds
  players_per_page: 13

  #How many players a page in a deeds book must contain to generate a new page for the group.
  players_for_new_page: 10

regions:
  #The minimum and maximum length a region name may have.
  names_length_limit:
    min: 4
    max: 24     # '-1' = no limit.

  #Defines what happens when on the event the player doesn't have the same permissions in two overlapping regiosns
  # - all: The player must have permission on all of them.
  # - any: The player must have permission on any ot them.
  # - oldest: The permissions of the oldest region take over.
  # - newest: the permissions of the newest region take over.
  overlapping_permissions_mode: all

  #Value in ticks that determines how ofter will the game check the players' locations to determine if they've physically entered of left a region.
  #Affects anything relying on PlayerEnterRegionEvent and PlayerLeftRegionEvent. Has no effect on abilities.
  #Any value equal or lower than 0 will disable player sampling.
  player_sampling_rate: 10

  border_display:
    #The following are merely visual settings. Set the particle used to define the walls of a region when a bell is ringed.
    particle:
      resolution: 1
      type: NAUTILUS    #Must be defined as a Spigot's Particle enum value. https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
      count: 1
      delta: [0,0,0]
      #Determines the rate in ticks in which the particles wall will be updated with new particles. The higher, the slower.
      refresh_rate: 10

    #How far can a player see the particles displaying the border of a region. Setting this too high could crash the server if a large region is displayed.
    show_radius: 15

    #How long in ticks will the region borders be displayed.
    persistence: 420

  # Configures the tittles to display whenever a players enters a region.
  name_title_display:
    enabled: true       # If true, a tittle with the region name will be shown to the player whenever they enter a region.
    fadeIn: 10          # The duration in ticks of the fade-in transition.
    stay: 30            # The duration in ticks the title will stay in the screen.
    fadeOut: 8          # The duration in ticks of the fade-out transition.
    refreshRate: 60     # The rate in ticks the plugin will check the regions the players are in.

  #The blocks considered as "crops", affected by the can_plant and can_break_crops abilities. Defined as a JSON list.
  #Must be filled with Spigot's Material enum values. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  plantable_blocks: [WHEAT, CARROTS, POTATOES, BEETROOTS, KELP, BAMBOO_SAPLING, SUGAR_CANE, BROWN_MUSHROOM, RED_MUSHROOM, NETHER_WART, ACACIA_SAPLING, SPRUCE_SAPLING, BIRCH_SAPLING, DARK_OAK_SAPLING, JUNGLE_SAPLING, OAK_SAPLING]

  #Defines the breakable redstone blocks. Those related to the can_break_redstone_blocks and can_place_redstone_blocks abilities.
  #Must be defined as Spigot's Material enum values. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  breakable_redstone_blocks: [REDSTONE_WIRE]

  #The buttons the plugin will consider as "enforced", affected by the can_press_enforced_buttons ability.
  #This allows having stronger buttons that only certain group members can press. Defined as a JSON list.
  #Must be filled with Spigot's Material enum values. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  enforced_buttons: [STONE_BUTTON, POLISHED_BLACKSTONE_BUTTON]

  #In Landlords Spigot you can use locked levers along with the can_pull_locked_levers ability to made only
  #certain group members pull a lever. To make a locked lever, a lever must be placed on a specific block.
  #This property defines such blocks. Defined as a JSON list.
  #Must be defined as a Spigot's Material enum value. https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  lever_locker_blocks: [COPPER_BLOCK, CUT_COPPER, EXPOSED_COPPER, EXPOSED_CUT_COPPER, WEATHERED_COPPER,
                        WEATHERED_CUT_COPPER, WAXED_COPPER_BLOCK, WAXED_CUT_COPPER, WAXED_EXPOSED_COPPER,
                        WAXED_EXPOSED_CUT_COPPER, WAXED_WEATHERED_COPPER, WAXED_WEATHERED_CUT_COPPER,
                        CUT_COPPER_SLAB, CUT_COPPER_STAIRS, EXPOSED_CUT_COPPER_SLAB, EXPOSED_CUT_COPPER_STAIRS,
                        WEATHERED_CUT_COPPER_SLAB, WEATHERED_CUT_COPPER_STAIRS, WAXED_CUT_COPPER_SLAB, WAXED_CUT_COPPER_STAIRS,
                        WAXED_EXPOSED_CUT_COPPER_SLAB, WAXED_EXPOSED_CUT_COPPER_STAIRS, WAXED_WEATHERED_CUT_COPPER_SLAB,
                        WAXED_WEATHERED_CUT_COPPER_STAIRS, IRON_BLOCK]